### ISSUE TITLE
guzzlehttp/guzzle is outdated

### ISSUE THREAD

**Issue by andraskende** [docusign/docusign-esign-php-laravel#2]
Trying to install this package but its guzzlehttp/guzzle  6.2 conflict with Laravel 9 - guzzlehttp/guzzle 7.2 version..

Thanks !

site@www:~/sites$ composer create-project laravel/laravel example-app

Creating a "laravel/laravel" project at "./example-app"
Info from https://repo.packagist.org: #StandWithUkraine
Installing laravel/laravel (v9.3.11)
  - Downloading laravel/laravel (v9.3.11)
...

site@www:~/sites/example-app$ composer require docusign/esign-laravel

Using version ^1.0 for docusign/esign-laravel
./composer.json has been updated
Running composer update docusign/esign-laravel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires docusign/esign-laravel ^1.0 -> satisfiable by docusign/esign-laravel[v1.0.0].
    - docusign/esign-laravel v1.0.0 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require docusign/esign-laravel:*" to figure out if any version is installable, or "composer require docusign/esign-laravel:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by sylvainleb376** [comment]
Hello,

Could you please follow the installation guide given in this article: https://www.docusign.com/blog/developers/send-document-laravel-jwt-grant-authentication
And check if the problem still appears.
Thanks and regards,

Sylvain

**Comment by AndyDunn** [comment]
The only installation instructions are literally "composer require docusign/esign-laravel". This library can't be used with current version of Laravel because of the conflict of guzzlehttp versions as mentioned above.

**Comment by stickyrst** [comment]
I have the same issue

**Comment by AndyDunn** [comment]
I ended up using one of the branched versions of this repo that fixed the issue and work. Not sure why DocuSign don't update the main branch themselves, or merge the changes already done by other devs.

**Comment by samsmith89** [comment]
Having the same issue

**Comment by Wossnap** [comment]
Same here.

**Comment by smd9788** [comment]
I've created an internal bug ticket for this issue: DCM-9041

**Comment by dbbrahmbhatt** [comment]
Fix has been added in the release [1.1.0](https://github.com/docusign/docusign-esign-php-laravel/releases/tag/v1.1.0)
